// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2lV0QDAO-6ZJ9Ky0ZwZ2ArEJvXbMntpk',
    appId: '1:98540195832:web:50f95730b1d4e0a36bd00d',
    messagingSenderId: '98540195832',
    projectId: 'muletrace-7993b',
    authDomain: 'muletrace-7993b.firebaseapp.com',
    storageBucket: 'muletrace-7993b.firebasestorage.app',
    measurementId: 'G-S5WS3DBV4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFMCe81LKVdCFI2xWOK4IY2XJJXR_g0fo',
    appId: '1:98540195832:android:f2cff180dd9cc2776bd00d',
    messagingSenderId: '98540195832',
    projectId: 'muletrace-7993b',
    storageBucket: 'muletrace-7993b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAibdZfv73QhcTuPXf5whWIIxZFFHeLByI',
    appId: '1:98540195832:ios:b033235fbe4a97086bd00d',
    messagingSenderId: '98540195832',
    projectId: 'muletrace-7993b',
    storageBucket: 'muletrace-7993b.firebasestorage.app',
    iosBundleId: 'com.example.projectSecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAibdZfv73QhcTuPXf5whWIIxZFFHeLByI',
    appId: '1:98540195832:ios:b033235fbe4a97086bd00d',
    messagingSenderId: '98540195832',
    projectId: 'muletrace-7993b',
    storageBucket: 'muletrace-7993b.firebasestorage.app',
    iosBundleId: 'com.example.projectSecure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2lV0QDAO-6ZJ9Ky0ZwZ2ArEJvXbMntpk',
    appId: '1:98540195832:web:8a7555771df539116bd00d',
    messagingSenderId: '98540195832',
    projectId: 'muletrace-7993b',
    authDomain: 'muletrace-7993b.firebaseapp.com',
    storageBucket: 'muletrace-7993b.firebasestorage.app',
    measurementId: 'G-JKK715318J',
  );
}
